// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

`define TV_IN_expandedKey_TDATA "../tv/cdatafile/c.AES_Encrypt.autotvin_expandedKey.dat"

`define AUTOTB_TRANSACTION_NUM 1

module AESL_axi_s_expandedKey (
    input clk,
    input reset,
    output [8 - 1:0] TRAN_expandedKey_TDATA,
    output TRAN_expandedKey_TVALID,
    input TRAN_expandedKey_TREADY,
    input ready,
    input done,
    output [31:0] transaction);

    wire TRAN_expandedKey_TVALID_temp;
    wire expandedKey_TDATA_full;
    wire expandedKey_TDATA_empty;
    reg expandedKey_TDATA_write_en;
    reg [8 - 1:0] expandedKey_TDATA_write_data;
    reg expandedKey_TDATA_read_en;
    wire [8 - 1:0] expandedKey_TDATA_read_data;
    
    fifo #(240, 8) fifo_expandedKey_TDATA (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(expandedKey_TDATA_write_en),
        .write_data(expandedKey_TDATA_write_data),
        .read_clock(clk),
        .read_en(expandedKey_TDATA_read_en),
        .read_data(expandedKey_TDATA_read_data),
        .full(expandedKey_TDATA_full),
        .empty(expandedKey_TDATA_empty));
    
    always @ (*) begin
        expandedKey_TDATA_write_en <= 0;
        expandedKey_TDATA_read_en <= TRAN_expandedKey_TREADY & TRAN_expandedKey_TVALID;
    end
    
    assign TRAN_expandedKey_TDATA = expandedKey_TDATA_read_data;
    assign TRAN_expandedKey_TVALID = TRAN_expandedKey_TVALID_temp;

    
    assign TRAN_expandedKey_TVALID_temp = ~(expandedKey_TDATA_empty);
    
    function is_blank_char(input [7:0] in_char);
        if (in_char == " " || in_char == "\011" || in_char == "\012" || in_char == "\015") begin
            is_blank_char = 1;
        end else begin
            is_blank_char = 0;
        end
    endfunction
    
    function [167:0] read_token(input integer fp);
        integer ret;
        begin
            read_token = "";
                    ret = 0;
                    ret = $fscanf(fp,"%s",read_token);
        end
    endfunction
    
    function [167:0] rm_0x(input [167:0] token);
        reg [167:0] token_tmp;
        integer i;
        begin
            token_tmp = "";
            for (i = 0; token[15:0] != "0x"; token = token >> 8) begin
                token_tmp = (token[7:0] << (8 * i)) | token_tmp;
                i = i + 1;
            end
            rm_0x = token_tmp;
        end
    endfunction
    
    reg [31:0] transaction_load_expandedKey_TDATA;
    
    assign transaction = transaction_load_expandedKey_TDATA;
    
    initial begin : AXI_stream_driver_expandedKey_TDATA
        integer fp;
        reg [167:0] token;
        reg [8 - 1:0] data;
        reg [167:0] data_integer;
        reg [8 * 5:1] str;
        integer ret;
        
        transaction_load_expandedKey_TDATA = 0;
        fifo_expandedKey_TDATA.clear();
        wait (reset === 1);
        fp = $fopen(`TV_IN_expandedKey_TDATA, "r");
        if (fp == 0) begin
            $display("ERROR: Failed to open file \"%s\"!", `TV_IN_expandedKey_TDATA);
            $finish;
        end
        token = read_token(fp);
        if (token != "[[[runtime]]]") begin
            $display("ERROR: token %s != [[[runtime]]]", token);
            $finish;
        end
        token = read_token(fp); // read 1st "[[transaction]]"
        forever begin
            @ (negedge clk);
            if (ready == 1) begin
                if (token != "[[[/runtime]]]") begin
                    if (token != "[[transaction]]") begin
                        $display("ERROR: token %s != [[[transaction]]]", token);
                        $finish;
                    end
                    token = read_token(fp); // skip transaction number
                    fifo_expandedKey_TDATA.clear();
                    token = read_token(fp);
                    while (token != "[[/transaction]]") begin
                        if (fifo_expandedKey_TDATA.full) begin
                            $display("ERROR: FIFO is full");
                            $finish;
                        end
                        ret = $sscanf(rm_0x(token), "%x", data_integer);
                        data = data_integer;
                        fifo_expandedKey_TDATA.push(data);
                        token = read_token(fp);
                    end
                    token = read_token(fp);
                    fifo_expandedKey_TDATA.snapshot();
                end else begin
                    fifo_expandedKey_TDATA.restore();
                    if (fp != 0) begin
                        $fclose(fp);
                        fp = 0;
                    end
                end
                transaction_load_expandedKey_TDATA = transaction_load_expandedKey_TDATA + 1;
            end
        end
    end

endmodule
