// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_AES_Encrypt (
unsigned char plaintext[16],
unsigned char expandedKey[240],
unsigned short Nr,
unsigned char ciphertext[16]);
