# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kuh4bd/Documents/FPGALab/Project_UART/ZynqComputerAES/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_AES_Full_0_1/Zynq_CPU_AES_Full_0_1.xci
# IP: The module: 'Zynq_CPU_AES_Full_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kuh4bd/Documents/FPGALab/Project_UART/ZynqComputerAES/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_AES_Full_0_1/constraints/AES_Full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_AES_Full_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/kuh4bd/Documents/FPGALab/Project_UART/ZynqComputerAES/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_AES_Full_0_1/Zynq_CPU_AES_Full_0_1.xci
# IP: The module: 'Zynq_CPU_AES_Full_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kuh4bd/Documents/FPGALab/Project_UART/ZynqComputerAES/ZynqComputer.srcs/sources_1/bd/Zynq_CPU/ip/Zynq_CPU_AES_Full_0_1/constraints/AES_Full_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_CPU_AES_Full_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
